### ISSUE TITLE
MUF and FuzzBall

### ISSUE THREAD

**Issue by ghost** [fuzzball-muck/fuzzball#209]
Just out of curiosity (no rush as the changes aren't urgent):
I noticed in the fuzzball repository, there's this directory:
dbs/advancedb/muf
It has the same stuff (pretty much) that the fuzzball-muf repository has.  When/how do changes move from fuzzball-muf to fuzzball itself?
I'm mostly used to mailing lists, so I apologise in advance for being so goofy with github. I don't know how else to contact you guys!  Thanks for reading my question!

**Comment by wyld-sw** [comment]
No worries; feedback@fuzzball.org works too, though GitHub is perfectly fine.

I'm unsure if the intention of fbmuf was to vet programs for direct inclusion in fuzzball. It was originally a folder inside the fbmuck distribution. However...

A while back I updated basedb with newer versions from fuzzball-muf, but I don't think I got around to finishing advancedb.

With FB7's release coming up, it's good to address these questions:
 Should all MUFs from fuzzball-muf be present in fuzzball itself?
 Is the distinction between basedb and advancedb clear? Should their contents change?
 Do we need additional databases?

**Comment by nyanster** [comment]
> I'm unsure if the intention of fbmuf was to vet programs for direct inclusion in fuzzball. It was originally a folder inside the fbmuck distribution. However...

It was originally included with fbmuck?  Interesting.  Then fbmuf should be preserved in some way, for the future.  Though, I wouldn't mind making a /old/ folder to move some of the oldest stuff into, and a README better explaining what these MUFs are and how to use (install) them.
> A while back I updated basedb with newer versions from fuzzball-muf, but I don't think I got around to finishing advancedb.

I think some stuff in advancedb might be newer than what's in fuzzball-muf.  Especially with advancedb, it's important to make sure not to overwrite a MUF with an older MUF, by carefully reading the diff between the two.
> With FB7's release coming up, it's good to address these questions:
> Should all MUFs from fuzzball-muf be present in fuzzball itself?

No.  Some of the MUF in fuzzball-muf is so specific, it wouldn't even belong in moderndb. (mentioned below)  THOUGH, I can imagine an exception.  It'd be possible, but not necessary, to create a demonstration db that _does_ demonstrate every single MUF (both from fuzzball's dbs and fuzzball-muf) somewhere in it, though not necessarily as globals.  It wouldn't be suitable as a db for creating new MUCKs from, but more to show people "how do I install and use these MUFs?  What props do they make and use?"
demodb would fit well in either the fuzzball-muf or fuzzball repositories.
> Is the distinction between basedb and advancedb clear? Should their contents change?

They are pretty distinct. advancedb has a lot more modern programs, especially stuff that uses color.  I don't think anything in basedb uses color, IIRC. advancedb seems to incorporate a lot of nice stuff from HLM.
I think basedb and advancedb (and of course minimaldb) shouldn't be added to (but changes and updates are alright!) since they provide a very different starting point than moderndb will provide.  So, keeping them as they are now does provide options to MUCK admins, thus not enforcing a monoculture of what MUFs people expect when they join a MUCK.  (for example, who's to say that **every** MUCK needs wi/rpwi?  Those'll be included in moderndb since they're so ubiquitous on large MUCKs today, though)
> Do we need additional databases?

Yes.  A new db called moderndb, which can, if any, be the database that includes more from fuzzball-muf.  moderndb would be the only db new commands are added to, other than the potential demodb. Thus, basedb and advancedb would (mostly) be in a feature freeze.  A README in the dbs folder would be useful to describe each db in a concise way.
Of course, this is just my vision.

Writing this reply because I'm looking back at my open issues. (and this one, I think, should stay open)  I also plan to (told Wyld this already, but posting it here too) make a trueminimaldb sometime, not to replace minimaldb but to see what would be the smallest working db, and make it also available.  Right now minimaldb has 195 lines, most of which are tunes.  trueminimaldb, if it's possible to remove tunes and have a working db (i.e., if fuzzball implies defaults for tunes not in a db) would be less than 40 lines.
This would be useful for checking the differences and similarities between the default behavior of Fuzzball itself and the defaults of the dbs.

**Comment by wyld-sw** [comment]
Yes, there are newer MUFs in advancedb - you’ll notice that fuzzball-MUF contains some “advanced” versions of programs - some supporting GUI operations, some for other reasons. We’ll consolidate where possible. 

Utilizing these MUFs to demonstrate features remains a good idea. 

I would be surprised if the sysparms in minimaldb differ from the default. One could certainly diff the first 160 or so lines of each dB and document any differences.
