### ISSUE TITLE
fbmuck fails to launch if logs directory does not exist

### ISSUE THREAD

**Issue by hyperlumic** [fuzzball-muck/fuzzball#235]
fbmuck (compiled from master at 2018-11-30 09:30 PM EST) with the following specified in `include/config.h`:

```
#define MUD_ID "fuzzball"
#define MUD_GID "fuzzball"
```

fbmuck launched from start script as root user fails if log directory does not already exist.

```
root@sprdev01:~ # /home/fuzzball/spr/restart
touch: /home/fuzzball/spr/game/logs/restarts: No such file or directory
/home/fuzzball/spr/restart: cannot create /home/fuzzball/spr/game/logs/restarts: No such file or directory
Unable to open logs/status!
Segmentation fault (core dumped)
```

Platform: `FreeBSD sprdev01.sprmuck.org 11.2-RELEASE-p5 FreeBSD 11.2-RELEASE-p5 #0: Tue Nov 27 09:33:52 UTC 2018     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64`

**Comment by nyanster** [comment]
There aren't many reasons why the logs directory wouldn't exist though: a user not copying the game directory post-install as detailed in README_LINUX.md, or the log directory being moved or deleted at some later date.  That's all I can think of.
https://github.com/fuzzball-muck/fuzzball/pull/237
But this diff fixes things so that fuzzball will start even if no logs directory already exists.
