### ISSUE TITLE
Built-in @register not strictly compatible with MUF version

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#281]
With the old @register MUF program, you could do a command with the following syntax:

`@register #prop #0:_reg/lib library-name=library-name`

This would work because the argument after the : can be *any* prop directory.

FB7's built in @register checks the prop directory against a list of propqueue names rather than allowing the targeting of arbitrary props cause reasons.  This is somewhat detrimental because old fogies like me have used @register in the past to set dbref props for instance, and some copy/paste scripts may rely on people doing stupid syntax like the syntax shown above.

Please note that I am aware that this equivalent does work:

`@register lib-name=lib/lib-name`

So ... this may be something you veto and say get with the times old man, but just pointing out that the new @register arbitrarily (from my perspective) restricts you from using different prop dirs and this is a major functional difference vs. the MUF-based @register.  I haven't tested this, but this may also cause problems if you are trying to register things on non-#0 and non-me targets.

I would recommend the help file emphasize that *only* prop queue directories are allowed if you keep it this way.

**Comment by kyanha** [comment]
I believe the in-driver version's intent was to facilitate creating personal and global registrations, not to replace the @register MUF.  The functionality it has in the driver is IIRC what's necessary to create portable MUF upload scripts that are guaranteed not to clobber anything and not require any state processing on the client.  cmd-@register.muf is designed to provide extended and expanded functionality.

The concern was to avoid bloating the driver with something that could be written in MUF.

That said, if the implementation doesn't match that essential purpose, I think it needs to be fixed/extended so that it can.

**Comment by tanabi** [comment]
Yeah, that's pretty funny, it is more bloat to restrict than to not restrict.  This is a very easy change and I'm happy to do it as my first contribution here.  I'll let you know if I find anything else funny (though it looked pretty good otherwise when I looked at it before).  I'll have a PR in later today.

**Comment by tanabi** [comment]
PR 282 resolves this.  https://github.com/fuzzball-muck/fuzzball/pull/282

**Comment by wyld-sw** [comment]
Thanks! I was hoping it'd be straightforward.
