### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#325]
Right now, compiling fuzzball, even with unmodified code, can lead to different binaries.  This is because fuzzball includes the date and time it was compiled in.
While the date and time are useful to curious users, and I check them often out of curiosity, are they entirely necessary?
As always, if I'm missing something about how something is useful, let me know.

What reproducible builds are:
A reproducible build is any build process, where if two people compile the same program, they get the same results.  (of course that's assuming the same OS, same hardware)
https://reproducible-builds.org/
https://wiki.debian.org/ReproducibleBuilds
https://en.wikipedia.org/wiki/Reproducible_builds
This means any two unmodified Fuzzball builds would have the same checksums.

GuixSD also does research on this:
https://www.gnu.org/software/guix/blog/2017/reproducible-builds-a-status-update/
> There’s a very practical advantage to reproducible builds: anyone who publishes binaries is in essence a mirror of our build farm.

I've done a test by compiling fuzzball, (```./configure --prefix=$PWD/here; make; make install```) renaming the folder **after** the compile, and compiling fuzzball again from a freshly unzipped folder. (it's important the folder names are the same during compile)  I've attached the diff.  This diff shows what prevents us from having a reproducible build, by showing what differs even in identical compiles.  The files config.log, fbmuck, version.c, and version.o differ.  Obviously, config.log is least important of those.

[rbdiff.txt](https://github.com/fuzzball-muck/fuzzball/files/2905006/rbdiff.txt)
[rbdiffu.txt](https://github.com/fuzzball-muck/fuzzball/files/2905007/rbdiffu.txt)

This makes me think.  Is mkversion useful?  I know it puts hashes into the program during compile.  But I think the usefulness of that can't go beyond "Yup, these files were modified by the MUCK admin before being compiled" for users.

**Comment by wyld-sw** [comment]
‘@hashes’ was explained to me as important for support. You are right that it basically lets us know if the MUCK is using the same copy of the file as the one published. Which might have been precisely the point.

Similarly, having the time and date helps us determine the actual version of the code. Of course, we could do that with a more granular version number or file creation time of the fbmuck binary.

I’m certainly willing to discuss the usefulness of mkversion and ‘@hashes’, but I wanted the support piece to be known.

@foxbird was one of the developers of this feature; Keet, what’s your take on this?

**Comment by nyanster** [comment]
> Similarly, having the time and date helps us determine the actual version of the code. Of course, we could do that with a more granular version number or file creation time of the fbmuck binary.

Exactly!  Replacing timestamps with version numbers (or git commit hashes or the like) is the recommended solution.  Is there a way to add a hook so that committers get bothered if they don't bump up a number somewhere in their commit?  Something like master-1 and the next commit updates it to master-2, etc, just bumping up once with every commit regardless of what the commit is.  With master-XXX being replaced by an actual version number (7.03, etc) when actually tagged for release.

I'll admit the time/date issue is mostly (but not entirely) separate from the mkversion issue, since mkversion would have the same hashes with unchanged files, hence wouldn't affect a reproducible build, to my knowledge.  My bad for combining them into one github issue. xP

**Comment by foxbird** [comment]
So, as  you mentioned, there are likely several different things happening here.

First, is the mkversion including the compiled on timestamp in the code. This most certainly will vary from machine to machine producing a different checksum in every build. Is it useful to have a timestamp of the build time? Yes and no. It does give you a general idea of when the build was produced so if you're curious about a binaries age and aren't a server admin (think assistant admin, someone on shared hosting, etc) that may not have access to a filesystem, it's got some minor value there. Otherwise, I'd argue that it's usefulness has been superseded beyond a neat amusement factor for people. It's also likely your prime culprit in getting clean reproducible builds.

Second, the incremental version number. I don't think this really helps the original developer any. But, for someone who may be trying out compile options, changing files, or customizing their code, it's got more merit. It's a poor man's local version number. We commit and distribute without the version file, so it'll always start fresh when compiling from a clean source. I don't think this would hurt the goal of a reproducible build, since two people with the same fresh code on the same environments would produce a version file with the same increment. Assuming it's their first build and all. Or that they make clobber/realclean/fresh/dist-clean/etc.

Third, is the use of hashes. These were added to help with support. A lot of the larger well established mucks tend to modify files to suit their own needs. If someone were to ask for support, seeing the hash output lets us know if there's a file that was changed and helps guide a search for issues. If we can't reproduce it, then it could be in a file we don't have that was altered. We can't rely on a baked in version number to each file as they aren't likely to change it when changing code. We also can't rely on anyone having git installed as they may have downloaded a zip instead of cloning. So, it was decided to add both a sha (or was it md5?) hash as well as the git hash. Both would help any support person figure out if changes were made.

You can always look for git commit hooks, but a commit can't put its own hash on a file until build time. An mkversion-like tool that runs and increments version numbers as part of a commit only solves part of the problem. So, as long as the need for support is there, you're kind of stuck with what you've got. Apparently even git itself puts the git hash into the build, so there's precedent for that. This just takes it one step further by hashing all files, and not just the hash of the commit.

On a personal note, I can honestly say I've never expected a locally built binary to ever match any checksum from anywhere. If I'm building something from source, there's a good chance I wanted to change something. I also don't really expect my system to be anything like anyone else's, so again, the hash will likely be different. Now, for those people with exactly identical setups, sure, I could see a mild expectation for it. I'm just not sure how practical it is to assume you and I will have the same environment. I don't see the overwhelming need to make this happen. The main argument seems to be for a chain of trust for compiled binaries, but I'm not sure we expect that chain to be intact. We are talking about people who will likely modify the code anyway before compiling, and also people who are not likely on the same build platforms. If this were a build farm situation or something akin to DRM checking, I might see more value in it for this application, but I don't. Beyond telling me 'someone probably changed -a- file in the source', it doesn't serve too much purpose except making me ask 'what file?'. I suspect this expectation just isn't valid for our situation as it stands. If that situation were to change, perhaps my opinion of the matter might.

If this is something that's essential for some solution my recommendation would be to remove the date field from the version file and then your binaries should be the same. Unless there is some gain we expect to get beyond 'some people are doing it so we should so', I don't recommend making any changes.

**Comment by tanabi** [comment]
My thought: Any of this dynamic information (hash, compile date, etc.) could be written to a text file as part of the make process, and make install would push that text file along with the binary to wherever the MUCK lives.

At MUCK load time (or at the time @ hashes is called or whatever command), load that file and get the information there.  This has the added benefit of this information being at the admin's fingertips when NOT logged into the MUCK; theoretically this file could be used to, for instance, do a version check against what is available here in GIT.

This would make the binary identical and consistent while also keeping all existing functionality and (arguably) adding additional functionality.

This all being said, this is an issue that has never bitten me before in a great many years of admining servers, so I personally don't feel like its a high priority item.  But if its something @nyanster wants to chase, I feel like this is the have-our-cake-and-eat-it-too approach.

**Comment by nyanster** [comment]
> Second, the incremental version number. I don't think this really helps the original developer any. But, for someone who may be trying out compile options, changing files, or customizing their code, it's got more merit. It's a poor man's local version number. We commit and distribute without the version file, so it'll always start fresh when compiling from a clean source. I don't think this would hurt the goal of a reproducible build, since two people with the same fresh code on the same environments would produce a version file with the same increment. Assuming it's their first build and all. Or that they make clobber/realclean/fresh/dist-clean/etc.

Yeah, it can be assumed that reproducible builds come from freshly unzipped code, so the incremental version probably isn't a problem.
> Third, is the use of hashes. These were added to help with support. A lot of the larger well established mucks tend to modify files to suit their own needs. If someone were to ask for support, seeing the hash output lets us know if there's a file that was changed and helps guide a search for issues. If we can't reproduce it, then it could be in a file we don't have that was altered. We can't rely on a baked in version number to each file as they aren't likely to change it when changing code. We also can't rely on anyone having git installed as they may have downloaded a zip instead of cloning. So, it was decided to add both a sha (or was it md5?) hash as well as the git hash. Both would help any support person figure out if changes were made.

True, seeing changes occurred can help in support.
> You can always look for git commit hooks, but a commit can't put its own hash on a file until build time. An mkversion-like tool that runs and increments version numbers as part of a commit only solves part of the problem. So, as long as the need for support is there, you're kind of stuck with what you've got. Apparently even git itself puts the git hash into the build, so there's precedent for that. This just takes it one step further by hashing all files, and not just the hash of the commit.

Ah, I see...
There is no NEED for support, just a DESIRE.  I think one of the best options available here is to just tell people they're on their own for modified code, which is what _every other software project does_ for support, and rightfully so.  Otherwise you're just debugging code you're never written and don't even know about.  Though, at that point, you still would have to just believe someone that they didn't change the code, if you didn't have hashes to confirm this.  But I like to believe people work in good faith.
But as the hashes don't affect reproducible builds, they can stay. :D
mkversion will stay too, then.
> On a personal note, I can honestly say I've never expected a locally built binary to ever match any checksum from anywhere. If I'm building something from source, there's a good chance I wanted to change something. I also don't really expect my system to be anything like anyone else's, so again, the hash will likely be different. Now, for those people with exactly identical setups, sure, I could see a mild expectation for it. I'm just not sure how practical it is to assume you and I will have the same environment. I don't see the overwhelming need to make this happen. The main argument seems to be for a chain of trust for compiled binaries, but I'm not sure we expect that chain to be intact. We are talking about people who will likely modify the code anyway before compiling, and also people who are not likely on the same build platforms. If this were a build farm situation or something akin to DRM checking, I might see more value in it for this application, but I don't. Beyond telling me 'someone probably changed -a- file in the source', it doesn't serve too much purpose except making me ask 'what file?'. I suspect this expectation just isn't valid for our situation as it stands. If that situation were to change, perhaps my opinion of the matter might.

It's meant for quite a few people and quite a few use cases, but not for everyone or every use case, true. 
 But fortunately, reproducible building doesn't stop people from modifying the source to make a modded version of Fuzzball, since they wouldn't be checking checksums for comparison.  But it's something that can benefit people who use vanilla Fuzzball code to start out with.
> If this is something that's essential for some solution my recommendation would be to remove the date field from the version file and then your binaries should be the same. Unless there is some gain we expect to get beyond 'some people are doing it so we should so', I don't recommend making any changes.

Yeah, I'm also thinking just removing the date and time.  It'll likely be impossible to anticipate other potential factors until after Fuzzball is in a few package repositories. (and packages are a major case in which reproducible builds lead to benefits, as mentioned on the Guix website: this applies to any binary distribution, actually, as this allows you to more greatly trust whoever you get a binary from)
**I'll look into removing the date and time and see if the diff shrinks to just config.log having changed.**

> My thought: Any of this dynamic information (hash, compile date, etc.) could be written to a text file as part of the make process, and make install would push that text file along with the binary to wherever the MUCK lives.
> 
> At MUCK load time (or at the time @ hashes is called or whatever command), load that file and get the information there. This has the added benefit of this information being at the admin's fingertips when NOT logged into the MUCK; theoretically this file could be used to, for instance, do a version check against what is available here in GIT.
> 
> This would make the binary identical and consistent while also keeping all existing functionality and (arguably) adding additional functionality.

I don't know if that'd count as a reproducible build, as something would differ in the final product, even if it weren't in the binary, but elsewhere in the build folder.  Doesn't sound bad though!  This might be better than what we have now.  Not sure.
> This all being said, this is an issue that has never bitten me before in a great many years of admining servers, so I personally don't feel like its a high priority item. But if its something @nyanster wants to chase, I feel like this is the have-our-cake-and-eat-it-too approach.

Yup!  I'll try to make this change myself. :D

**Comment by wyld-sw** [comment]
This may have already been in your plan, but if you remove the date and time, please change the version number (it can even be 7.00b1.20190226) while we continue to discuss solutions going forward.

**Comment by nyanster** [comment]
After:
https://github.com/fuzzball-muck/fuzzball/pull/327
https://github.com/fuzzball-muck/fuzzball/commit/d7db810273978c4ef804ad2211bef12da7dea4a7
indeed, the diff between two different compiles shrinks to only having a line in ```config.log``` change.
I consider this a success.  Closing the issue now~
