### ISSUE TITLE
@register data leak

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#331]
The '@ register' built-in command allows you to casually browse props on whatever you want.

For instance:
```
@register #prop SomePlayer:/
```
will list props on SomePlayer.  Fortunately, @ register only understands 'ref' style props.  So, string values show up as INVALID.  That's why I'm posting this as a public bug and not quietly fixing it myself :)  But you can still see a player's prop structure which is an info leak.

The MUF version does proper permission checking.

@ register does do proper checking when trying to set a prop it looks like.  It also makes sure that the player cannot set wizard properties.  Its just read that isn't done right.

**Comment by nyanster** [comment]
> That's why I'm posting this as a public bug and not quietly fixing it myself :)

Bugs should always be public. :P

Interesting info leak, though...

**Comment by tanabi** [comment]
> > That's why I'm posting this as a public bug and not quietly fixing it myself :)
> 
> Bugs should always be public. :P
> 
> Interesting info leak, though...

If its a serious security hole, it should probably be private until its fixed, so that server admins can patch it before its widely known.  This isn't quite a serious security hole, but its not great.  Fortunately most MUCKs use the MUF-based @ register anyway.

**Comment by wyld-sw** [comment]
I’d agree that it’s a bug. The original intent was that it would only work on ‘me’ and #0, but we may be beyond that.

**Comment by nyanster** [comment]
> If its a serious security hole, it should probably be private until its fixed, so that server admins can patch it before its widely known. This isn't quite a serious security hole, but its not great. Fortunately most MUCKs use the MUF-based @ register anyway.

I meant that in general, BUT
I unfortunately have experience with a lot of MUCK wizzes.  If bugs aren't public, a large number of them would have no reason to care, since they'd just feel relieved their users haven't heard about it.  So they'd do nothing about it.  And a lot of them still don't care even when a bug is public: but if a bug is public, at least the users would know.  See
https://github.com/fuzzball-muck/fuzzball/issues/297
for an example of a bug where only one MUCK's wizzes responded out of all the MUCKs I contacted.
Keeping bugs secret is a disservice to people who enjoy MUCKing.
And by private, private to which cabal?  Who are the Chosen Ones?  How do you figure out which developers and which wizzes you trust?  Does anyone know every MUCK in existence?  What happens to the non-famous MUCKs that aren't privately told?
Keeping bugs private lead to the huge fiascos like KRACK, and Intel's CPU bugs being fixed and worked around far more slowly than they could be. (I'm sure the CIA and NSA were happy about both these things: they encourage it)
I'm also sure if the Mac OS X bug "press enter twice to get root" would've never been told to users if it were reported privately instead of publicly on Twitter.

**Comment by nyanster** [comment]
> The details of those bugs will not be shared publicly at this time. I can understand the need to have these things private.

Fuck you.

**Comment by tanabi** [comment]
@nyanster if I find a security hole, I'm going to fix it before making it public, because there are like ... 3 developers on this project.  Making it pre-emptively public helps literally nobody except people who want to exploit it.

If a user finds a security hole, they're more than welcome to post it public and we'll fix it as fast as we can.  I'm not advocating conspiracies or keeping it private for any length of time, but I am advocating a little bit of common sense.  If you find a bug you're unable to personally fix, then report it, security or otherwise, and publically if you like (though I tend to think if its something serious you should notify @wyld-sw privately, but, I'd rather it be reported publically than not reported at all).  But if its in your means to fix it, then fix it first, then make it public so that people can patch right away.

I'm NOT suggesting we should tell any server admins about a security hole ahead of others.  Either its public or not.  No secret cabal, just an attempt to not cause our admins any unnecessary hardship :)

**Comment by tanabi** [comment]
@wyld-sw I got this one next (Unless you've already done it ;) )

**Comment by wyld-sw** [comment]
Go for it!
