### ISSUE TITLE
config.h includes a lot of nonconfigurable items

### ISSUE THREAD

**Issue by ghost** [fuzzball-muck/fuzzball#366]
I noticed the typedef of dbref to int is in config.h, and there's the entire "don't change anything below here!" section.
I feel config.h should ONLY have stuff users are meant to read and configure.  It shouldn't have any "internal use" stuff. I advocate moving stuff like the dbref typedef to something like fbmuck.h  (or maybe defines.h)
Right now I'm working on a pull request that puts more includes where they belong, and I'm having to include config.h an awful lot, just for dbref.

**Comment by wyld-sw** [comment]
What do we think about removing the typeset and just using int? I understand the need to categorize variables, but I feel that can be done with proper naming - especially since I see these variables being numeric for the foreseeable future.

**Comment by nyanster** [comment]
> What do we think about removing the typedef and just using int? I understand the need to categorize variables, but I feel that can be done with proper naming - especially since I see these variables being numeric for the foreseeable future.

You don't think dbrefs might change size in the future?  While an int is 2billion+ on many machines, that's not the case on all machines.  But I think **a separate issue should be made for dbref/typedef stuff**, since, as in a previous comment elsewhere, I noticed that some of fbmuck's typedefs aren't used consistently, and there's likely more to explore.
But you're right, dbref could be changed to an int or long or something.

In any case, this issue still applies...  config.h has a lotta stuff.

**Comment by tanabi** [comment]
> What do we think about removing the typedef and just using int? I understand the need to categorize variables, but I feel that can be done with proper naming - especially since I see these variables being numeric for the foreseeable future.

I actually like the type, personally.  And if we ever went to C++ we could use the 'dbref' type as an object potentially if that had any value (I'm not saying it does, since that sounds like a pretty heavy implementation to me, but for the sake of argument keeping it as a type keeps our options open).

Anyway, I do think its pretty crazy that config.h has a don't change section -- but that was incredibly common back when this was written.  So if you can sort out where everything goes that's great.

**Comment by tanabi** [comment]
> > What do we think about removing the typedef and just using int? I understand the need to categorize variables, but I feel that can be done with proper naming - especially since I see these > But you're right, dbref could be changed to an int or long or something.

A dbref could be an int, long, short, a struct or a class, all depending on the needs of its implementers in the future.  I think practically speaking it would always be a numeric value, but may as well keep the option open :)

**Comment by wyld-sw** [comment]
Exactly. I hadn't considered that, once we move toward an object-oriented approach, the object itself could have value.

**Comment by nyanster** [comment]
> once we move toward an object-oriented approach

?
This is news to me.

**Comment by wyld-sw** [comment]
This can be utilizing C to encapsulate similar functions in specific areas, or discussing interspersing C++ within the code to more elegantly handle things like string buffers and tightly associating functions with structures.

**Comment by tanabi** [comment]
> > once we move toward an object-oriented approach
> 
> ?
> This is news to me.

We have a lot of redundant code that is basically redundant because we don't have a way to do real inheritance.  For instance, we have many different tree structures implemented, some of which have near 100% overlap but have very subtle differences that mean you can't quite use, say, the AVL tree from properties with the AVL tree for MUF dictionaries.

There's a lot of common checking and processing that would also benefit from an OO approach.  I'd like to consider, in the future, considering moving parts or all of the MUCK to C++ but in a carefully planned and considered way.  MUCKs are, almost literally, object oriented by nature so it seems a good fit.

"If" would have been a better word than "when", there's no actual plan from anybody to do this I don't think. It's just something that seems logical.

**Comment by wyld-sw** [comment]
Yeah, bad word choice on my part. In my mind, I (and now we) have already been moving toward object-oriented (or object-based) with the refactoring over the last couple years. I do agree about C++ offering many benefits.

@tanabi, I know you mentioned a roadmap before; let's all discuss reachable milestones going forward after the release of the next beta (which should be shortly after the this phase of the doc project is complete!).
