### ISSUE TITLE
Question about M1

### ISSUE THREAD

**Issue by nyanster** [fuzzball-muck/fuzzball#374]
It's a common practice on MUCKs to give everyone Builder.  Also, unlike ProtoMUCK, there's no Meeper flag, so everyone can use MPI.
**What'd the consequences be, if I were running a MUCK, of giving _everyone_ the M1 bit?**  This sounds like a very attractive idea, and seems harmless to me.  BUT since I don't see this already on any MUCKs I use, I wonder if there might be something I'm not seeing, or don't know about.

(wyld, when you see this issue, please label it "question")

**Comment by wyld-sw** [comment]
This is of course currently up to the individual MUCK admins - they can add a 1 to the sysparm pcreate_flags - though I don’t know how many softcoded pcreates respect that (would be simple with the upcoming SETFLAG or SETFLAGS prim). Changing the sysparm value in one or all of the included databases is an interesting idea.

**Comment by wyld-sw** [comment]
Never mind - I think that both NEWPLAYER and pcreate check that sysparm!

**Comment by wyld-sw** [comment]
Speaking of Proto, I think their @ powers system is intriguing - and may give us the ability to define existing permissions in terms of these powers (can use MPI, can use MUF, can use connection functions/primitives, etc.). This isn’t the same power list from Proto, but I think it could be a good example. 

Another proto idea I like is their sysparm alt_infinity_handler, for more standard float error handling. It’s referenced in a current Issue and may go a long way towards cleaning up some float-based TODOs.

**Comment by nyanster** [comment]
> This is of course currently up to the individual MUCK admins - they can add a 1 to the sysparm pcreate_flags - though I don’t know how many softcoded pcreates respect that (would be simple with the upcoming SETFLAG or SETFLAGS prim). Changing the sysparm value in one or all of the included databases is an interesting idea.

Of course this is up to MUCK admins, as it should be.  I wasn't actually thinking of changing that value in the databases...  Though that IS intriguing!  (definitely not all, though.  moderndb or advancedb maybe)
I was mostly thinking consequences in terms of whether there are exploits, or whether M1 MUF could use substantially more CPU/memory than MPI does.  Anything like that?  If no-one knows of any downsides, whenever I eventually do run a MUCK, everyone will have M1.

> Speaking of Proto, I think their @ powers system is intriguing - and may give us the ability to define existing permissions in terms of these powers (can use MPI, can use MUF, can use connection functions/primitives, etc.). This isn’t the same power list from Proto, but I think it could be a good example.
> 
> Another proto idea I like is their sysparm alt_infinity_handler, for more standard float error handling. It’s referenced in a current Issue and may go a long way towards cleaning up some float-based TODOs.

https://github.com/fuzzball-muck/fuzzball/issues/79
Yeah, our math could be cleaned up a lot. xP  I want to figure out what to do with infinity and huge_val, because it's more of the "lets assume we don't even have C89" typedef hell we've seen before. :B
"alt_infinity_handler: Makes it so that all the math prims follow IEEE standard to the letter, as opposed to the conventions that currently exist in the prims. [Alynna]"  Sounds pretty good to me, though I wonder about backwards compatibility.  Before fb7 release is a good time for breaking compatibility, though. :D

**Comment by tanabi** [comment]
@nyanster There's a few downsides, though as always, it is up to you to determine how severe it is.

Creating programs makes files on your disk, and it would relatively easy for a malicious person to fill your disk drive.  You could argue that someone could do the same with DB objects, but I believe you could @ program a MUF and just stream however much crap you want in there (as long as each like is under BUFFER_LEN) and I don't think there's any limit to it.  You wouldn't need any special scripting to do this like you would need to fill the disk by creating DB objects, and the size of programs is not limited by any quota which is something you can use to limit DB growth.

Granted, that is a long shot and a weird attack vector, but you asked for downsides and that's one.

MUCKER permissions haven't been as closely scrutinized as MPI permissions I don't think.  I think the irony here is MPI is generally more permissible than an M1, though, but I think an M1 has more abilities to access things like remote properties if I remember right (which I may not TBH :)  It has been a long time since I've been an M1 on a MUCK).

Due to the way Fuzzball is, each implementation of each feature is repeated 2 or 3 times and often implemented slightly different each time.  You've got the @-command version if applicable, the MUF version, and the MPI version of each.  Giving blanket M1's to folks opens your MUCK up to additional vectors for unknown attacks.  I think if we unified the Fuzzball backend code so that there's one source of authority for each 'API call' it would remove this risk, but we're not there yet.

That's what I can think of ... I think aside from wading into the waters of unintended consequences, there's not a huge reason to not allow M1's.  That being said, would I do it?  Nope.  What I would do in your shoes is make an authorization program.  A little MUF that sets the M1 bit and makes your players agree to use it responsibly.  You can automate people getting the bit while also reminding them that its a privilege.  That is what the MUCK "founding fathers" intended with the MUCKER bits, for it to be something of a privilege, and therefore it is likely even at an M1 level that a player has more powers than your average Joe.

And now you're 2 cents richer :)  Good luck!

**Comment by nyanster** [comment]
Thank you so much!  This is the sort of info I was looking for.
I suppose the usual of taking regular backups to other machines and not giving the user fbmuck runs under the entire hard drive already deals with anything M1 could possibly cause to go wrong.
Good to know~  I'll close this issue in a couple days or so.

**Comment by tanabi** [comment]
> Thank you so much! This is the sort of info I was looking for.
> I suppose the usual of taking regular backups to other machines and not giving the user fbmuck runs under the entire hard drive already deals with anything M1 could possibly cause to go wrong.
> Good to know~ I'll close this issue in a couple days or so.

Another kind of related to filling the hard drive -- A lot of @ quota programs will report the number of programs a user owns, but I don't think there's any way to limit it.  Because you can't programmatically enter the MUF editor, so you can't wrap ```@program and @edit```.  So that means you could have people just making lots of programs and never cleaning up after themselves which isn't great.

What you could do if you cared about this, is make your own MUF editor and use program_setlines to set the lines.  Actually this could be used to make a way more friendly MUF editor and could be something you'd like to do in general if you want to encourage new MUF-ers.

Speaking of program_setlines, another attack vector you could do with MUF is you could fill an array up with huge near-BUFFER_LEN strings.  An M1 can only fill an array to the point where you run out of instructions -- but that's still a rather large number, and there's nothing stopping you from running multiple copies of the program.  Array sizes are not limited -- for some reason I thought they were (probably because many of the array_get_prop* calls *are* limited in size) -- I just checked the code and there is no limitation on array_insertitem

This kind of attack would be really hard to do in MPI.  Again, this is a real long shot, there's no real benefit to the player to crash a MUCK this way except for the joy of anarchy I guess :)
