### ISSUE TITLE
Git Shenanigans -- needs .gitignore ?

### ISSUE THREAD

**Issue by tanabi** [fuzzball-muck/fuzzball#401]
So the auto-restart script on the dev MUCK is rebooting every hour.  This is because when I pull from GIT I am getting:

```
fuzzball@preview:~/fuzzball$ git pull origin master
From https://github.com/fuzzball-muck/fuzzball
 * branch            master     -> FETCH_HEAD
Updating b2f29ee..3d64747
error: Your local changes to the following files would be overwritten by merge:
	docs/man.txt
	docs/mufman.html
Please, commit your changes or stash them before you can merge.
Aborting
```

I guess the build process generates those files, but we're also committing them to git, which makes a conflict.  I would propose putting these files in .gitignore but I would like someone who understands the build process better to approve it (I'm looking at @wyld-sw  or @nyanster )

**Comment by tanabi** [comment]
@nyanster tells me this is because windows can't run prochelp, so this is part of windows support.

In that case, I can just alter my script to git checkout -- docs/man.txt  (and the other doc files) and we can leave it as-is for now.

**Comment by tanabi** [comment]
Added this to my script:
```
git checkout -- docs/*
```
should fix it ... I'll close this, we can clean this up when we decommission the other windows specific weirdnesses.

**Comment by nyanster** [comment]
I wonder, though.  Why are the local documents changing, compared to those on github?  I'd think the same .raw would be converted to the same .txt and .html every time...  I didn't think it was nondeterministic.
Will the documentation still update on the devmuck?

**Comment by tanabi** [comment]
We have noticed that the documentation doesn't always update on make install -- like on Hope Island, make install doesn't re-install the docs.  However, on Wyld's dev machine, it does install docs.  I haven't made a ticket for it because I haven't spent the time to quantify the problem.  It is probably a  /usr/bin/install difference between Linux and Mac.

**Comment by wyld-sw** [comment]
> Why are the local documents changing, compared to those on github?

I think it's because their modification time is different. Not 100% sure.

> We have noticed that the documentation doesn't always update on make install.

Would it be disruptive if we used 'mv' instead? For me, that was the expected behavior. But I may not be otherwise.

**Comment by tanabi** [comment]
> Would it be disruptive if we used 'mv' instead? For me, that was the expected behavior. But it may not be otherwise.

The purpose of 'install' is to make sure the ownership of the file is proper, specifically when doing a system level install (for example, installing with no ```--prefix``` option).  I would recommend as a "best practices" measure to try and cooperate with the install program if possible.  Note that 'fbmuck' is copied using install and it does seem to be moved over correctly, so it is possible.

Further, you should probably never use mv to relocate build artifacts outside of the source code structure.  cp would be the right command for the job if you're going to do it that way.  You'd only mv if you were relocating the files within the source structure (for example, if we wanted to relocate all the binaries to a "dist" folder).  That way, the installation process is "non destructive" and repeatable.  If you move the files, a subsequent make install would error out.  Why would you make install twice?  Maybe you manually deleted something by accident (I've done it before :P) and you need to!

**Comment by wyld-sw** [comment]
Wow, yeah. I meant cp, sorry. But if there's a way to cooperate with install, let's do that!

**Comment by nyanster** [comment]
> We have noticed that the documentation doesn't always update on make install -- like on Hope Island, make install doesn't re-install the docs. However, on Wyld's dev machine, it does install docs. I haven't made a ticket for it because I haven't spent the time to quantify the problem. It is probably a /usr/bin/install difference between Linux and Mac.

> on Hope Island, make install doesn't re-install the docs

Correct.  For better or for worse, make install does not update anything in the $PREFIX/game directory.  That includes documentation.  Presumably, this is to not overwrite any data that may be customized on an already-running, merely-upgrading-and-not-a-fresh-install MUCK, which may include customized documentation.  Hence the last few steps mentioned in README_UNIX.md

> However, on Wyld's dev machine, it does install docs

Can you clarify?  I don't think this is possible, so I want to understand.  During make install, make help is run, which regenerates the .txt and .html files in place in Fuzzball's docs/ directory, and then also puts them in your OS's (or prefix's) doc/ directory, but does not put it into the $PREFIX's game/ directory, which is what the MUCK uses for help files.  It places them into the tarball's game/ directory, for manual copying later.

> It is probably a /usr/bin/install difference between Linux and Mac.

I think this is unlikely.
(also it's really unfortunate that Apple took down most of Mac OS X's man pages from their website: it's difficult or impossible for me to try to check behavior for programs now, since for some reason, they're not on web.archive.org)

> I think it's because their modification time is different. Not 100% sure.

Ahh, interesting. \*nod\*

> Would it be disruptive if we used 'mv' instead? For me, that was the expected behavior. But it may not be otherwise.

I think we should continue using install rather than cp, unless we find a reason to switch.  I know install does some things to avoid race conditions and to ensure a running daemon will still run correctly after install.

I've checked that all the .txt and .html files in the repository are up to date, btw...  @tanabi , where is $PREFIX on muck.fuzzball.org, and where do you keep the git repo?  I'm curious.

**Comment by nyanster** [comment]
I wonder if upgrading the documentation in ```make install``` is OK.  I think the possibility or value of customized man.txt, help.txt, and mpi.txt is really low.

**Comment by wyld-sw** [comment]
> I think this is unlikely.

Confirmed; making a change to mufman.raw and then running 'make install' overwrites game/data/man.txt for me. I realize this isn't expected.

> I wonder if upgrading the documentation in make install is OK.

I'm fine with whatever changes to the makefile make the most sense :)

> I'd be willing to hear about positive reasons to customize it, though. :D

I've heard of MUCKs creating a news, man, mpi, or help subfolder for their documentation files. Probably where `News has subtopics! Type 'news index' to ...` gets its functionality. (Though that may need to be reworded there's no `news index` built in currently.). However, to your point, I wouldn't expect folks to update the three main auto-generated files.

**Comment by wyld-sw** [comment]
No clue how recent this is, but: https://ss64.com/osx/install.html

This /might/ be relevant, but I may have trouble parsing it:

> If the target file already exists, it is either renamed to file.old if the -b option is given or overwritten if permissions allow.

**Comment by wyld-sw** [comment]
My $PREFIX does allow me to write into game/data, so that's probably at least part of the reason. It allows me to update the repository easily, but I'll be mindful that it's not a usual process.

**Comment by nyanster** [comment]
> Confirmed; making a change to mufman.raw and then running 'make install' overwrites game/data/man.txt for me. I realize this isn't expected. Let me know if I can provide any specific details.

In $PREFIX/game???  Woah.  You're not using PWD as your PREFIX, are you??  You shouldn't be, if you are!  There's a reason why I have the CI have PREFIX be $PWD/fuzzpre and not just $PWD.  A prefix of $PWD itself is a unique situation that can't model any other prefix someone might use for Fuzzball, because that prefix means some of Fuzzball's folders end up already inside prefix, even when not installed there.
For new installs, I imagine prefixes will usually be either an all-new folder in someone's home directory, or the root of the filesystem itself.
This means for development, doing something like $PWD/something and $HOME/something are good choices for prefixes.  Later on, before 7.00 release, we will have to use some machines where we can test using things like ```/``` and ```/usr/local``` as prefixes.

**What do you give to configure as prefix, I wonder...**
and I still wanna know from @tanabi what prefix he's using on the dev MUCK
I think knowing what prefixes everyone's using (for any and all purposes) might solve this problem.
I myself do ```$PWD/here``` which is identical, other than for the name, to the ```$PWD/fuzzpre``` used in our CI configuration.

> Also, I consider the lack of man pages online for Darwin a bug, and will file a report; maybe just got missed, since the developer docs are usually focused on iOS/macOS apps. Reporting may do some good...

I think they intentionally removed them, as while section 1 of the manual is all gone, some other sections remain.  But if you could ask for them to be put back online again, that'd be pretty useful.
Fortunately, Solaris man pages are available online, when looking at POSIX and SysV things, but I rarely find the need to use them.  In this case it seems like they use GNU install nowadays.

> I'm fine with whatever changes to the makefile make the most sense :)

> I've heard of MUCKs creating a news, man, mpi, or help subfolder for their documentation files. Probably where `News has subtopics! Type 'news index' to ...` gets its functionality. (Though that may need to be reworded as there's no `news index` built in currently.). However, to your point, I wouldn't expect folks to update the three main auto-generated files.

Makes sense.  I also thought "If anything, there might be extra files in info/"
I'll see what I can do to update the .txt documentation in $PREFIX/game/data/ without altering $PREFIX/game/ in any other ways, in a way that's easy to read and understand.

> My $PREFIX does allow me to write into game/data, so that's probably at least part of the reason. It allows me to update the repository easily, but I'll be mindful that it's not a usual process.

Details?  But, yeah, that's possible.

**Comment by tanabi** [comment]
> I've checked that all the .txt and .html files in the repository are up to date, btw... @tanabi , where is $PREFIX on muck.fuzzball.org, and where do you keep the git repo? I'm curious.

/home/fuzzball/fuzzball (git repo)
/home/fuzzball/muck (prefix)

**Comment by nyanster** [comment]
> > I've checked that all the .txt and .html files in the repository are up to date, btw... @tanabi , where is $PREFIX on muck.fuzzball.org, and where do you keep the git repo? I'm curious.
> 
> /home/fuzzball/fuzzball (git repo)
> /home/fuzzball/muck (prefix)

Thanks!
I wonder why we're having any problems then. :v  I guess it might be from timestamps...  What does git show you if you try to get a diff output of what it thinks all the changes are?

**Comment by tanabi** [comment]
> I wonder why we're having any problems then. :v I guess it might be from timestamps... What does git show you if you try to get a diff output of what it thinks all the changes are?

I can't anymore, I already re-checked out the 'bad' files.  Sometimes I get this same issue on my linux workstation, I'll see if I can reproduce it.
