### ISSUE TITLE
$IFDEF not working as expected

### ISSUE THREAD

**Issue by dbenoy** [fuzzball-muck/fuzzball#477]
I expected this to compile but it aborts.

```
@program testprog.muf
1 99999 d
i
$DEF TEST 3

$IFDEF TEST<1
  $ABORT TEST
$ENDIF

: main ( s --  )
;
.
c
q
```

**Comment by wyld-sw** [comment]
It seems that if I replace `$def TEST 3` with `$define TEST 3 $enddef`, it behaves.

A quick test shows that the '$define` sets the value to " 3", while the `$def` sets it to "3". I think the former uses next_char directly, which includes the space - while the latter uses next_token.

Assuming this doesn't cause more issues, should we restructure $define to use next_token as well?

**Comment by tanabi** [comment]
@wyld-sw Sorry for not pitching in on this.  You should use next_token -- I have actually been bitten by this before as well.  I can think of no useful case where nibbling that initial unavoidable space is useful.

**Comment by wyld-sw** [comment]
Turns out I couldn't just use next_token. Some of the $def'd values may include spaces. An example of this is in advancedb (watchfor, #80):

```$def prop_spam $iflib $lib/away "_prefs/wf/away?" $else "_prefs/wf/spam?" $endif```

So I added a call to skip_whitespace before getting the value of next_char.

Commit: b8c36fc0ba6cbf8d431915c0e2dd7fb9ddc74ff4

Let me know if there's an issue.
