### ISSUE TITLE
Pasting a large amount of text (description, MUF program, etc.) causes player to disconnect

### ISSUE THREAD

**Issue by sypherspace** [fuzzball-muck/fuzzball#48]
Multiple players have reported that pasting a large block of text causes their connection to drop. After reconnecting, repasting the same text tends to succeed, though in rare cases, several disconnects may occur before the paste attempt succeeds. Most recently, this occurred while I was attempting to paste a 131-line MUF program into the editor.

**Comment by sypherspace** [comment]
Add: Even `@list`ing a long MUF program will occasionally cause my connection to die. I haven't been able to replicate this behavior when not connected via SSL/TLS.

**Comment by sypherspace** [comment]
Still there.

**Comment by wyld-sw** [comment]
Does anyone have ideas on a testing plan for this? I still can't replicate it, though I know can be a rare occurrence.

@woggle, @kyanha ? Thanks in advance.

**Comment by aidanPB** [comment]
This might be pointing fingers fruitlessly, but given that sypherspace can't replicate the issue on cleartext connections, might the cause lie in their SSL/TLS library?

**Comment by sypherspace** [comment]
Debian stable's OpenSSL library? I'd find that difficult to believe.

**Comment by aidanPB** [comment]
I'd forgotten your setup; I wouldn't have suggested it if I had remembered that you were using jessie and its OpenSSL.

**Comment by sypherspace** [comment]
And I didn't mean to sound like a dick in my response, sorry! That was pre-lunch.

**Comment by kyanha** [comment]
I'm not sure that I'd particularly blame the stable OpenSSL library, but I
am more than willing to hypothesize that the problem might lie in fbmuck's
use of it.

I am unfortunately not currently set up to debug it.  Wog, are you?

-Winged

**Comment by kittykitty71** [comment]
Was asked to add my two bits in, so for what it's worth...  

For nostalgic reasons, I have my term set to limit everything to a 80 x 40 characters, and because I'm often insanely verbose, I find myself hitting enter on blocks that wind up more than half the screen.  Say 50 - 70 'lines' in one continuous input string.  Almost invariably, this will drop my client.  I can then immediately re-connect and it (as stated up top) re-sends just fine using the history buffer.

I would also not be at all surprised if it's connected to some strange call / error dealing with the SSL lib, though as yet I have no hard data either way.  Will continue to do what user-end debugging I can and report any further discoveries if and as I make them.

**Comment by kittykitty71** [comment]
Digging around, I came across some potentially related information.
https://sourceforge.net/p/fbmuck/bugs/122/

Admittedly, I don't know much at this point about what's exactly going on 'under the hood', so clearly if that's entirely irrelevant, ignore as appropriate.  In the off chance it's connected and helpful though, I figured I'd err on the side of TMI since, it'd be REALLY nice if this could be fixed.  xD

**Comment by kyanha** [comment]
What happened with sourceforge bug 122 was a combination of factors.

1) SSL is stateful, meaning if you try to use an old state on a connection
which had a state that advanced, you will irreparably harm the connection
and so it will close.
2) fbmuck can fork() to do its database saves in the background.
3) When fbmuck finished saving, the fork()ed version would be the one that
wrote the "dump done" message.
4) When a process fork()s, it copies the current state of the process,
including the current states of all of its SSL connections.
5) The entire point of the fork() is so that players can continue to do
additional things before the dump is complete.  This causes the states on
those connections to advance.  But, the states in the fork()ed process
weren't updated.
6) As a result of #1, when the fork()ed process wanted to complete point
#3, the state advancement of point #5 caused the connections to close.
(And if they didn't close immediately, those writes themselves would cause
the state of the connection to advance, so the next time the
main/unfork()ed process tried to write, the connections would close at that
point.)

I don't think this current bug fits the same pattern, as all connections
and data transfers are happening within the main process.

-Winged

**Comment by sypherspace** [comment]
Any word on this? I'm sorry to nudge, but this is a colossally annoying issue when trying to modify code, descriptions, etc.

**Comment by wyld-sw** [comment]
I have not seen or heard of the issue being replicated outside of SPR, but maybe I haven't been listening well enough. Personally, I have not experienced it inside SPR, though I know it happens.

I'm open to suggestions, because I am at a loss Thanks for your patience; it's frustrating to the dev team as well.

Sent from my iPhone

On Sep 10, 2017, at 12:46 PM, Justin Coffman <notifications@github.com<mailto:notifications@github.com>> wrote:


Any word on this? I'm sorry to nudge, but this is a colossally annoying issue when trying to modify code, descriptions, etc.

-

**Comment by sypherspace** [comment]
Just rebuilt SPR on latest code and Debian 9.2. I haven't gotten this to reproduce even in instances where it was incredibly reliable prior to the updates. I'll keep trying to trigger this and let you know.

**Comment by kyanha** [comment]
What was the prior platform?  Figuring out what the underlying system
library differences between them were might be instructive.

-Winged

**Comment by sypherspace** [comment]
Previous: Debian 8.8, stock OpenSSL, stock GCC.
Current: Debian 9.2, stock OpenSSL, stock GCC.

I can no longer get this to reproduce under any circumstances. I'll query the players to see if anyone else noticed this and now doesn't.

**Comment by sypherspace** [comment]
One other that previously experienced the issue can no longer get this to occur. Maybe an edge-case with Debian 8's OpenSSL?

**Comment by wyld-sw** [comment]
Glad it's working. Feel free to reopen if this issue resurfaces.

**Comment by kittykitty71** [comment]
Late to the party, but I'd also just like to add confirmation that as of recently (Not sure how long, health issues had me away a while) this issue is resolved.  Accidentally or otherwise  ;)
