### ISSUE TITLE
We need a DUMP prim!

### ISSUE THREAD

**Issue by cyveris** [fuzzball-muck/fuzzball#537]
Currently, the only configurable for database dumps is how often. We'd like to be able to configure dumps to happen at a specific server time, e.g. hourly **on the hour**, similar to a cron job.

**Comment by wyld-sw** [comment]
How about an option (`@tune cron_program`?) that specifies a MUF to run every so often, and expose dumping as a wizard primitive?

Just an idea. Let me know if it's not feasible.

**Comment by cyveris** [comment]
That sounds perfect, really. The purpose behind the request is ensuring internal consistency for regular backups/rsync jobs. Don’t want to accidentally get into a timing where rsync is occurring during a dump.

**Comment by cyveris** [comment]
That could be perfect. The purpose behind the request is ensuring internal consistency for regular backups/rsync jobs. Don’t want to accidentally get into a timing where rsync is occurring during a dump.

The question is how often the `cron_program` would run, and how we'd ensure that it runs at the minute desired.

**Comment by wyld-sw** [comment]
What are your thoughts on that? I was thinking it could run every minute as you might expect - which doesn't seem like it would be an issue normally. Could be completely wrong though.

**Comment by cyveris** [comment]
That's as often as anything in a crontab or `cron.d` file would be executed. I don't see an issue there.

**Comment by wyld-sw** [comment]
Could also have a `@tune cron_interval` defaulting to 1m if there's a need to change it for performance reasons.

**Comment by cyveris** [comment]
Love it!

**Comment by tanabi** [comment]
Here's a couple more thoughts on this --

A 'crond' could actually be very easily programmed in MUF.  There's no particular reason to server-side this.  If you'd like me to write this, I could probably do it pretty closely.

If we're going to bake it into the server, I'd want to make it more flexible than to run a single MUF at some interval ... to me that seems like barely better than writing crond in MUF :)

**Comment by tanabi** [comment]
If crond is written in MUF, we can make it basically work like real cron.  Could even use the same interval format and a proplist of entries.  Such as:

```
5 * * * * \#12345 This Goes On Stack
```

would call \#12345 every hour at the 5 minute mark.

**Comment by cyveris** [comment]
We already have that. There are two things we need: The ability to disable database dumping via tune, and a wizard-level prim that allows a dump to be performed in MUF.

**Comment by tanabi** [comment]
> We already have that. There are two things we need: The ability to disable database dumping via tune, and a wizard-level prim that allows a dump to be performed in MUF.

Ah, good point, we'd need a DUMP prim.  That should be super easy to make, a nice 5 minute change.  As for disabling DB dumping in tune -- When you manually dump it actually resets the dump timer.  as long as your DB dump interval is greater than your MUF dump interval, this should never come up -- and leaving dumps on will give you a safety net.

**Comment by cyveris** [comment]
Sounds great!

**Comment by tanabi** [comment]
I'll work on the DUMP prim as soon as I'm done with the documentation stuff -- I'll probably get to it tonight -- assuming @wyld-sw doesn't beat me to it.  It should seriously only take about 15 minutes to do, and 10 minutes of that will be testing :)

**Comment by wyld-sw** [comment]
Apologies.. my cron_program idea was for a crond to read a crontab - I probably should have made that clear :)

**Comment by tanabi** [comment]
@wyld-sw Yeah sounds like this really turned into "we need a DUMP prim" which is a much easier and quicker problem to solve :)

**Comment by cyveris** [comment]
Could we also have fbmuck accept an unused signal via kill to trigger a dump?

**Comment by tanabi** [comment]
@cyveris I think it might already do that -- have to double check.  I know there was a discussion in the issues about signals about a year ago.  However, I think regardless, a DUMP prim is an excellent idea as there are many cases for it.  We can also look into a signal (or verify if a signal exists)

**Comment by tanabi** [comment]
@cyveris I found the issue re. signals that I mentioned and funny enough it is one of yours :)

https://github.com/fuzzball-muck/fuzzball/issues/307

SIGHUP reloads config, SIGUSR1 / SIGUSR2 do legacy features we don't know if folks are using or not.  We would either have to re-task one of those signals (which in the past we've been reluctant to do since we don't know if those are features people use) or add a new signal.

With the DUMP prim, you could actually use MCP to trigger a dump if you wanted.  If this use case is useful to anyone, I can write the muf and some sample python that does it.  I'm not opposed to a signal, but I feel like its really murky as to which signal we'd support for this whereas an MCP trigger is pretty "not murky" IMO.

**Comment by cyveris** [comment]
Haha, oops! I'd appreciate the MUF/Python that we could use to trigger a dump. Is it possible to make the DUMP prim have a synchronous option, so that it doesn't return until the dump is completed?

**Comment by tanabi** [comment]
> Is it possible to make the DUMP prim have a synchronous option, so that it doesn't return until the dump is completed?

I was actually thinking about this.  So ... the way the MUCK is constructed, when it does a DB dump and async dumps are enabled, it forks a process to do the dump and then it immediately returns the dump call so the MUCK doesn't hang while it dumps.

Our options here would be to either (a) deal with it being async and accepting this is the world we live in (which sucks), (b) let DUMP take a parameter to choose between async dump and sync dump -- with the latter being the kind of dump that locks up the whole MUCK just like in the FB5 days (which also sucks), or .... (c) let async dump use the MUF "events" system to send an event which your MUF program can wait for.  Which is pretty cool IMO but the events system is kind of "voodoo" code and not the easiest to deal with.

I'm going to try to make [c] happen.  If I can make that work, I'll also provide a sample MUF handling events because I think very few people other than me have programmed MUF event handlers :)

**Comment by cyveris** [comment]
That would be amazing, honestly. Like I said, the intent here is to set up a backup system for SPR (among others) that can guarantee internal consistency at backup time. In an ideal world, I could run a single backup script that connects, dumps, returns when the dump is complete, then runs a borg backup on the muck's game dir.

**Comment by tanabi** [comment]
If I can make it work the optimal way, I'll provide a python + MCP script that does the dump and waits for the dump to finish.

If I can't make it work the optimal way, I'll stil provide the python + MCP but you'll have to choose between living in an unpredictable world or locking up your MUCK while it waits :)  I'll do my best.  

Anyway, I'll assign this one to me since this is getting more and more into my 'specialization zone' of odd MUF edge cases :)  I'll start working on it in a minute and hopefully have you something soon.

**Comment by tanabi** [comment]
Ugh, finishing up the documentation project took longer than I thought it would (...tunelist.h is a jerk :) ) and basically took me all night to finish, but it's finished, and I will add this prim in tomorrow for you.  Sorry for the delay!

**Comment by cyveris** [comment]
All good! Thanks again.

**Comment by tanabi** [comment]
@cyveris I'm almost done with this.  Code is complete, I'm just hitting it repeatedly to make sure there's no memory leaks or other weirdnesses.

One weirdness is, the MUF event wait queue is apparently processed really infrequently ... an event can sit for a good 10 seconds, maybe a little more, before it is reported to the program.  This isn't great, but for your purposes (wanting to wait until the dump is done to run a backup) this should be fine.

Another 'weirdness', or something you should be aware of, is the scheduled dump also does a number of cleanup events -- specifically it cleans out programs that have been sitting in memory but haven't been used in awhile, and it cleans up a few other MUF related items.  Manually triggered dumps do not do this cleanup.  However, it looks like these are run on their own timer in addition to being tripped by the dump process, so I am not sure this is a concern.  If you notice your MUCK using a lot more memory, this is probably the reason and we should dig into it more.

However, unless you're running on a SPARC 5 or a DECStation from the late 80's I am dubious you would notice any memory differenec :)

**Comment by cyveris** [comment]
> an event can sit for a good 10 seconds, maybe a little more, before it is reported to the program

I'm looking at hourly processes, so a 10-15 delay is not a problem. :)

> If you notice your MUCK using a lot more memory, this is probably the reason and we should dig into it more.

I'll keep an eye out, but yeah. Probably not a big deal.

Thanks again for all the help!

**Comment by tanabi** [comment]
Okay!  So I finished this, when the PR gets reviewed and merged it will be ready.

In "scripts" you will find two new buddies.  trigger-dump.muf and trigger-dump.py

trigger-dump.muf is basically an altered version of mcp-extern that will allow you to trigger a dump.  It can be merged into mcp-extern if you are already using it if you wish ... or just run 2 separate processes, it won't hurt that much, but I hate to have two processes running that do the same thing myself :)

trigger-dump.py is a script that will trigger the dump and wait for it.  If you are python savvy, you might want to add a timeout to the process() loop at the bottom, so that if it takes more than like 30 seconds it exits or throws some error in a place you will see it.  You can do this simply by capturing time.time() prior to entering the loop, and staying in that loop until 30 seconds have passed.

It uses my pyfuzzball library for MCP comms.  If you need help getting this set up I can give more details, I dunno how Pythonriffic you are :)  My library lives here: https://github.com/tanabi/pyfuzzball

**Comment by tanabi** [comment]
This is done, ping me if you need help getting any of it set up.

**Comment by cyveris** [comment]
Works like a champ!
