### ISSUE TITLE
NEXTDESCR skips descriptors on the welcome screen

### ISSUE THREAD

**Issue by wyld-sw** [fuzzball-muck/fuzzball#565]
This primitive may be the only one that ignores descriptors that aren't fully connected. Is this expected?

**Comment by tanabi** [comment]
I believe this is expected behavior as I discovered during refactor.  This prim is used by 3who for example to iterate over descriptors.  If we want to be able to capture users on the welcome screen, we should make a separate primitive set for it (since firstdesc / lastdescr obey the same connected-only rule).  Since there's no demand for this or immediate use for that matter that I can see ... I'd say close this one :)

**Comment by wyld-sw** [comment]
Gotcha, and agreed. I found this “discrepancy” during a refactor; only fitting it is resolved during one too :)
