### ISSUE TITLE
Consider making descriptors and connection numbers synonymous

### ISSUE THREAD

**Issue by wyld-sw** [fuzzball-muck/fuzzball#566]
DESRCON and CONDESCR would be no-ops. Look into this further to see if this is feasible.

**Comment by wyld-sw** [comment]
I think this makes a lot of sense (was @tanabi's idea). I'm trying to think of when someone would need to use the connection numbers directly. Sure, you could do `1 contime`, but is there a use case for something like that? Is there something (besides DESRCON) that returns a connection number?

This might be another case of introducing something new (descriptors in MUF) but wanting to still support the previous method for a while. I could be missing something, for sure.

If we did this, maybe:
- Alias CONBOOT, CONDBREF, CONDESCR, CONHOST, CONIDLE, CONNOTIFY, CONTIME, and CONUSER to their DESCR* counterparts.
- Keep CONCOUNT (potentially rename/alias to DESCRCOUNT).
- Make CONDESCR and DESCRCON no-ops.
- Test with common MUFs that use CON* primitives.

**Comment by wyld-sw** [comment]
Oh ... "looping from 1 to CONCOUNT" might be a use case for the connection numbers. If that's the case, do we alias things like CONIDLE to CONDESCR DESCRIDLE, and "hide" those CON* primitives from normal use?

Hmm.

**Comment by tanabi** [comment]
> Oh ... "looping from 1 to CONCOUNT" might be a use case for the connection numbers. If that's the case, do we create in-server defines for things like CONIDLE, to be CONDESCR DESCRIDLE?
> 
> Hmm.

This DOES potentially make a complication ... on Hope Island there's only 1 program that does such a loop (cmd-3who.muf) so I think this is a lot more common with older MUFs.  It may just be a breaking change and perhaps we fix MUFs in fbmuf github.  We could make a "generator" style call (kind of like NEXT .... NEXTDESCR ? ) so that instead of doing a 1 ... CONCOUNT loop, you can loop on NEXTDESCR for a similar experience.  That would be a very simple change and easy for folks to port to.

**Comment by tanabi** [comment]
Looks like NEXTDESCR already exists :)

**Comment by wyld-sw** [comment]
#645 maps CON* in-server defines to DESCR* counterparts. Please review.

This will break existing MUF code that relies on concount loops, but the fix for that situation is straightforward (see change to starterdb's 85.m). At the very least we'll need a communication plan ( and possibly links to updated program(s) )before this goes live.

**Comment by tanabi** [comment]
@wyld-sw I have reviewed your PR in detail ... I want to do a little more testing, but, I'm pretty sure the use case of concount to iterate over all users is fairly slim.  Some MUCKs may have custom WHO's that may have gotchyas, but I think we'll be okay in the majority case.

We may want to advise the SPR and Spin Dizzy folks to basically 'grep' their MUF directory for CONCOUNT and be ready to fix those MUFs.  Otherwise, I'm inclined to say let's bite the bullet and merge this (after a smidge more testing).

**Comment by wyld-sw** [comment]
Agreed. Thanks for being thorough.

**Comment by tanabi** [comment]
@wyld-sw I haven't fogotten about this, I will try to finish my testing today :)  @skylerbunny @jcoffm this one might impact your MUCKs.

**Comment by Loonesbury** [comment]
I'm a bit late, but I didn't pull a fresh copy of FB7 until recently.

I understand wanting to remove seemingly-unnecessary code, but I will point out that players can be connected more than once; simply changing CON to DESCR doesn't get you the same behavior. This also makes it rather annoying to get a list of online players without duplicates.

I understand that's a relatively rare use case, but I wanted to put that on the record.
